#!/bin/bash

OLD_MAIL=$1
NEW_MAIL=$2

if [ -z "$OLD_MAIL" ] || [ -z "$NEW_MAIL" ]; then
  echo "Usage: $0 [old-mail] [new-mail]"
  exit 1
fi

git filter-branch -f --commit-filter 'if [ "$GIT_AUTHOR_EMAIL" = "'$OLD_MAIL'" ];
  then export GIT_AUTHOR_EMAIL='$NEW_MAIL';
  fi; git commit-tree "$@"' -- --branches --tags


